// Run with `npm test` in proxy/.

import assert from "node:assert/strict";
import { test } from "node:test";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";
import { crc32, deflateRawSync, inflateRawSync } from "node:zlib";
import Fastify, { type FastifyBaseLogger } from "fastify";
import { cleanLua, cleanPackageLuas, stripLuaComments } from "./luaClean.js";
import { sanitizeLua } from "./luaSanitize.js";
import { FileCache } from "./fileCache.js";
import { ProviderCooldown } from "./merged.js";
import { registerDepotRoutes, type DepotUpstreams } from "./routes/depot.js";
import type { RawStream } from "./depotbox.js";

const log = { info() {}, warn() {}, error() {} } as unknown as FastifyBaseLogger;

/** What providers actually wrap their Luas in: banners, links, timestamps, disabled pins, notes. */
const PROVIDER_LUA = [
  "-- Generated by SomeProvider.net | join discord.gg/someprovider",
  "-- Created: 2026-09-25 14:02:11",
  "--[[",
  "  Thanks for using our service!",
  "]]",
  "addappid(3751260) -- Main game",
  'addappid(3751261, 1, "fe44cc16911c3d5dabb2b862a70f1b8b58ee79e1da1f47b8bf03af487c17e8fc") --Mainappid',
  '-- setManifestid(3751261, "6667172545766883229")',
  "",
  "addappid(4417540) --[==[ DLC: Soundtrack ]==]",
  "",
].join("\r\n");

test("provider comments go, the code stays, and Drydock's header is on top", () => {
  const cleaned = cleanLua(PROVIDER_LUA, "3751260");
  assert.equal(
    cleaned,
    [
      "-- Drydock unlock | App 3751260",
      "-- https://github.com/NhMarco/Drydock",
      "addappid(3751260)",
      'addappid(3751261, 1, "fe44cc16911c3d5dabb2b862a70f1b8b58ee79e1da1f47b8bf03af487c17e8fc")',
      "addappid(4417540)",
      "",
    ].join("\n"),
  );
});

test("cleaning a clean Lua changes nothing", () => {
  const once = cleanLua(PROVIDER_LUA, "3751260");
  assert.equal(cleanLua(once, "3751260"), once);
});

test("a double dash inside a string is not a comment", () => {
  assert.equal(stripLuaComments('print("a -- b") -- note'), 'print("a -- b") ');
  assert.equal(stripLuaComments("x = 'it''s -- fine' --x"), "x = 'it''s -- fine' ");
  assert.equal(stripLuaComments('s = "esc \\" -- still string" -- gone'), 's = "esc \\" -- still string" ');
  assert.equal(stripLuaComments("t = [[ -- long string ]] -- gone"), "t = [[ -- long string ]] ");
});

test("block comments of any level, inline or across lines", () => {
  assert.equal(stripLuaComments("a --[[ one ]] b"), "a  b");
  assert.equal(stripLuaComments("a --[==[ ]] still ]==] b"), "a  b");
  assert.equal(stripLuaComments("a --[[\nline\n]]\nb"), "a \nb");
  // An unterminated block comment runs to the end, as in Lua.
  assert.equal(stripLuaComments("a --[[ never closed"), "a ");
});

test("the sanitizer still sees the commented pins when it runs first", () => {
  // The order the Lua route uses: sanitize (reads `-- setManifestid`), then clean.
  const raw = ["addappid(900)", "addappid(901)", '-- setManifestid(901,"5")'].join("\n");
  const sanitized = sanitizeLua(raw);
  assert.equal(sanitized.removed, 1);
  assert.equal(
    cleanLua(sanitized.body, "900"),
    "-- Drydock unlock | App 900\n-- https://github.com/NhMarco/Drydock\naddappid(900)\n",
  );
});

// --- ZIP ---------------------------------------------------------------------------------------

interface ZipInput {
  name: string;
  data: Buffer;
  deflate?: boolean;
  /** Sizes and CRC in a data descriptor after the data, as streaming writers do. */
  descriptor?: boolean;
}

/** A minimal but real ZIP writer, independent of the one under test. */
function buildZip(entries: ZipInput[], comment = ""): Buffer {
  const parts: Buffer[] = [];
  const directory: Buffer[] = [];
  let offset = 0;
  for (const entry of entries) {
    const compressed = entry.deflate ? deflateRawSync(entry.data) : entry.data;
    const crc = crc32(entry.data) >>> 0;
    const name = Buffer.from(entry.name);
    const flags = entry.descriptor ? 0x0008 : 0;
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(flags, 6);
    local.writeUInt16LE(entry.deflate ? 8 : 0, 8);
    local.writeUInt32LE(entry.descriptor ? 0 : crc, 14);
    local.writeUInt32LE(entry.descriptor ? 0 : compressed.length, 18);
    local.writeUInt32LE(entry.descriptor ? 0 : entry.data.length, 22);
    local.writeUInt16LE(name.length, 26);
    const descriptor = Buffer.alloc(entry.descriptor ? 16 : 0);
    if (entry.descriptor) {
      descriptor.writeUInt32LE(0x08074b50, 0);
      descriptor.writeUInt32LE(crc, 4);
      descriptor.writeUInt32LE(compressed.length, 8);
      descriptor.writeUInt32LE(entry.data.length, 12);
    }
    const record = Buffer.alloc(46);
    record.writeUInt32LE(0x02014b50, 0);
    record.writeUInt16LE(20, 4);
    record.writeUInt16LE(20, 6);
    record.writeUInt16LE(flags, 8);
    record.writeUInt16LE(entry.deflate ? 8 : 0, 10);
    record.writeUInt32LE(crc, 16);
    record.writeUInt32LE(compressed.length, 20);
    record.writeUInt32LE(entry.data.length, 24);
    record.writeUInt16LE(name.length, 28);
    record.writeUInt32LE(offset, 42);
    directory.push(record, name);
    parts.push(local, name, compressed, descriptor);
    offset += local.length + name.length + compressed.length + descriptor.length;
  }
  const directoryBytes = Buffer.concat(directory);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(directoryBytes.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(Buffer.byteLength(comment), 20);
  return Buffer.concat([...parts, directoryBytes, end, Buffer.from(comment)]);
}

/** Reads a ZIP the way an unzip tool does, checking every CRC. */
function readZip(zip: Buffer): Map<string, Buffer> {
  let end = zip.length - 22;
  while (end >= 0 && zip.readUInt32LE(end) !== 0x06054b50) end -= 1;
  assert.ok(end >= 0, "end of central directory");
  const count = zip.readUInt16LE(end + 10);
  let cursor = zip.readUInt32LE(end + 16);
  const files = new Map<string, Buffer>();
  for (let index = 0; index < count; index += 1) {
    assert.equal(zip.readUInt32LE(cursor), 0x02014b50);
    const method = zip.readUInt16LE(cursor + 10);
    const crc = zip.readUInt32LE(cursor + 16);
    const size = zip.readUInt32LE(cursor + 20);
    const nameLength = zip.readUInt16LE(cursor + 28);
    const extra = zip.readUInt16LE(cursor + 30);
    const commentLength = zip.readUInt16LE(cursor + 32);
    const local = zip.readUInt32LE(cursor + 42);
    const name = zip.subarray(cursor + 46, cursor + 46 + nameLength).toString();
    assert.equal(zip.readUInt32LE(local), 0x04034b50, `local header of ${name}`);
    // The local header must agree with the directory (what a streaming unzip relies on).
    assert.equal(zip.readUInt32LE(local + 14), crc, `local CRC of ${name}`);
    const start = local + 30 + zip.readUInt16LE(local + 26) + zip.readUInt16LE(local + 28);
    const compressed = zip.subarray(start, start + size);
    const data = method === 8 ? inflateRawSync(compressed) : Buffer.from(compressed);
    assert.equal(crc32(data) >>> 0, crc, `CRC of ${name}`);
    files.set(name, data);
    cursor += 46 + nameLength + extra + commentLength;
  }
  return files;
}

const MANIFEST = Buffer.from(Array.from({ length: 4096 }, (_, index) => (index * 7) % 251));

test("the Lua in a package is cleaned and every other file is kept byte for byte", () => {
  for (const [deflate, descriptor] of [
    [false, false],
    [true, false],
    [true, true],
  ] as const) {
    const zip = buildZip(
      [
        { name: "3751261_6667172545766883229.manifest", data: MANIFEST, deflate, descriptor },
        { name: "3751260.lua", data: Buffer.from(PROVIDER_LUA), deflate, descriptor },
        { name: "keys/readme.txt", data: Buffer.from("-- not a lua, left alone"), deflate },
      ],
      "provider comment on the archive",
    );
    const files = readZip(cleanPackageLuas(zip, "3751260"));
    assert.equal(files.size, 3);
    assert.deepEqual(files.get("3751261_6667172545766883229.manifest"), MANIFEST);
    assert.equal(files.get("3751260.lua")?.toString(), cleanLua(PROVIDER_LUA, "3751260"));
    assert.equal(files.get("keys/readme.txt")?.toString(), "-- not a lua, left alone");
  }
});

test("the header names the App ID from the Lua's own file name", () => {
  const zip = buildZip([
    { name: "10_1.manifest", data: MANIFEST },
    { name: "480.lua", data: Buffer.from("addappid(480) -- x") },
  ]);
  const lua = readZip(cleanPackageLuas(zip, "999")).get("480.lua")?.toString() ?? "";
  assert.ok(lua.startsWith("-- Drydock unlock | App 480\n"), lua);
});

test("a package that is clean already, or cannot be read, is passed through untouched", () => {
  const clean = buildZip([
    { name: "10_1.manifest", data: MANIFEST },
    { name: "480.lua", data: Buffer.from(cleanLua("addappid(480)", "480")) },
  ]);
  assert.equal(cleanPackageLuas(clean, "480"), clean);
  // No central directory (a truncated or odd archive): nothing is guessed at.
  const headersOnly = clean.subarray(0, clean.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02])));
  assert.equal(cleanPackageLuas(headersOnly, "480"), headersOnly);
  // A Lua whose CRC does not match is not rewritten from damaged bytes.
  const damaged = Buffer.from(
    buildZip([{ name: "480.lua", data: Buffer.from("addappid(480) -- x") }]),
  );
  damaged[30 + "480.lua".length] ^= 0xff;
  assert.equal(cleanPackageLuas(damaged, "480"), damaged);
});

// --- The route ---------------------------------------------------------------------------------

function raw(body: Buffer): RawStream {
  return { stream: Readable.from([body]), contentLength: body.length, contentType: "application/zip" };
}

test("the depot route serves the cleaned package, also from a copy cached before the cleaning", async () => {
  const dir = await mkdtemp(join(tmpdir(), "drydock-clean-"));
  const app = Fastify();
  const providerZip = buildZip(
    [
      { name: "70_8765.manifest", data: MANIFEST, deflate: true },
      { name: "70.lua", data: Buffer.from(PROVIDER_LUA), deflate: true },
    ],
  );
  try {
    const upstreams = {
      depotbox: { downloadDepotPackage: async () => raw(providerZip) },
    } as unknown as DepotUpstreams;
    const cache = new FileCache(dir, 60_000, log);
    registerDepotRoutes(app, upstreams, ["depotbox"], cache, async () => {}, new ProviderCooldown());

    const fresh = await app.inject({ url: "/v1/depot/package/70" });
    assert.equal(fresh.statusCode, 200);
    assert.equal(readZip(fresh.rawPayload).get("70.lua")?.toString(), cleanLua(PROVIDER_LUA, "70"));
    assert.equal(Number(fresh.headers["content-length"]), fresh.rawPayload.length);

    // A package cached by an older proxy: the raw provider ZIP, stored before this process started.
    await cache.put("depot:71", Readable.from([providerZip]), "application/zip");
    const hash = createHash("sha1").update("depot:71").digest("hex");
    const metaPath = join(dir, "filecache", `${hash}.json`);
    const meta = JSON.parse(await readFile(metaPath, "utf8")) as { storedAt: number };
    await writeFile(metaPath, JSON.stringify({ ...meta, storedAt: Date.now() - 60 * 60 * 1000 }));
    const cache2 = new FileCache(dir, 24 * 60 * 60 * 1000, log);
    const app2 = Fastify();
    registerDepotRoutes(app2, upstreams, ["depotbox"], cache2, async () => {}, new ProviderCooldown());
    const old = await app2.inject({ url: "/v1/depot/package/71" });
    await app2.close();
    assert.equal(old.headers["x-cache"], "HIT");
    assert.equal(readZip(old.rawPayload).get("70.lua")?.toString(), cleanLua(PROVIDER_LUA, "70"));
    assert.deepEqual(readZip(old.rawPayload).get("70_8765.manifest"), MANIFEST);
  } finally {
    await app.close();
    await rm(dir, { recursive: true, force: true });
  }
});
